name: Deploy to Netlify

on:
  push:
    branches: [ main, master ]
    paths:
      - 'support_website/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'support_website/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Netlify CLI
      run: npm install -g netlify-cli
      
    - name: Deploy to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: |
        cd support_website
        netlify deploy --prod --dir=. --site=${{ secrets.NETLIFY_SITE_ID }} 