name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Analyze code
      run: flutter analyze || true
      
    - name: Run unit tests
      run: flutter test
      
    - name: Run integration tests
      run: flutter test integration_test/
      
    - name: Build iOS (simulation)
      run: flutter build ios --no-codesign
      
    - name: Build Android (simulation)
      run: flutter build apk 